### ISSUE TITLE
A non-null Infinispan cache implementation is required

### ISSUE THREAD

**Issue by vadimkim** [kazuhira-r/infinispan-getting-started#1]
Building and running **remote-spring-session** application generates the following error:

`2018-03-12 16:14:47.630 ERROR 12899 --- [ost-startStop-1] o.s.b.c.embedded.tomcat.TomcatStarter    : Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'springSessionRepositoryFilter' defined in org.infinispan.spring.session.configuration.InfinispanRemoteHttpSessionConfiguration: Unsatisfied dependency expressed through method 'springSessionRepositoryFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionRepository' defined in org.infinispan.spring.session.configuration.InfinispanRemoteHttpSessionConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.infinispan.spring.session.InfinispanRemoteSessionRepository]: Factory method 'sessionRepository' threw exception; nested exception is java.lang.IllegalArgumentException: A non-null Infinispan cache implementation is required
`

**Comment by kazuhira-r** [comment]
Infinispan's Spring Session needs to create a cache named "sessions" by default.

Could you create a cache called "sessions" on Infinispan Server and try again?
http://infinispan.org/docs/9.0.x/user_guide/user_guide.html#externalizing_session_using_spring_session
https://github.com/infinispan/infinispan/blob/9.0.3.Final/spring/spring4/spring4-remote/src/main/java/org/infinispan/spring/session/configuration/EnableInfinispanRemoteHttpSession.java#L44

**Comment by vadimkim** [comment]
Thank you, @kazuhira-r, for fast reply. I have tried to create "sessions" using infinispan configuration XML file and it works. Didn't find how to do it programmatically, but you gave me a good reference! Will try it.
I was testing Hazelcast cache before and "sessions" cache was created there by autoconfiguration. Though it is a bug you code, but it is rather feature of the infinispan configuration. You can close the issue.
